sudo: required
services:
  - docker

before_install:
  - docker pull daroczig/grpc:latest

script:
  - >
    docker run -v `pwd`:/grpc daroczig/grpc /bin/bash -c "
    cd /tmp &&
    Rscript --vanilla -e \"devtools::build('/grpc')\" && 
    R CMD INSTALL /tmp/grpc*.tar.gz &&
    Rscript --vanilla -e \"library(testthat);test_package('grpc')\"
    "
