sudo: required
services:
  - docker

before_install:
  - docker pull daroczig/grpc:latest

script:
  - >
    docker run -v `pwd`:/grpc daroczig/grpc /bin/bash -c "
    cd /tmp &&
    Rscript --vanilla -e \"devtools::install_local('/grpc')\" && 
    Rscript --vanilla -e \"library(testthat);test_package('/grpc')\"
    "
